WebForum/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebForum.BLL.Interfaces;
using WebForum.BLL.Models;
using WebForum.PL.ViewModels;
using WebForum.PL.ViewModels.Admin;

namespace WebForum.PL.Controllers
{
    [Route("admin")]
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ITopicService _topicService;
        private readonly IMapper _mapper;

        public AdminController(
            ITopicService topicService,
            IMapper mapper)
        {
            _topicService = topicService;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet("topics")]
        public async Task<ActionResult> TopicsAsync(int page = 1)
        {
            var result = new AdminTopicViewModel();

            if (page == 1)
            {
                result.TotalCount = await _topicService.GetCountAsync();
            }

            var activities = await _topicService.GetPagedAsync(page);

            result.Page = page;
            result.Topics = _mapper.Map<IEnumerable<Topic>, IEnumerable<TopicViewModel>>(activities);

            return View(result);
        }

        [HttpGet("topics/create")]
        public ActionResult CreateTopicAsync()
        {
            var viewModel = new TopicViewModel();

            return View(viewModel);
        }

        [HttpPost("topics/create")]
        public async Task<ActionResult> CreateTopicAsync(TopicViewModel requestVm)
        {

            var request = _mapper.Map<TopicViewModel, Topic>(requestVm);

            await _topicService.CreateAsync(request);

            return Redirect("~/admin/topics");
        }

        [HttpPost("topics/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTopic(Guid id)
        {
            await _topicService.DeleteAsync(id);

            return Redirect("~/admin/topics");
        }        
    }
}

WebForum/Controllers/UsersController.cs
using WebForum.DAL.Models;
using WebForum.PL.ViewModels.Account;
using WebForum.PL.ViewModels.Admin;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebForum.PL.Controllers
{
    public class UsersController : Controller
    {
        UserManager<UserEntity> _userManager;

        public UsersController(UserManager<UserEntity> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index(int page = 1)
        {

            var result = new AdminUsersViewModel();

            if (page == 1)
            {
                result.TotalCount = _userManager.Users.Count();
            }


            result.Users = _userManager.Users.Skip((page - 1) * 15).ToList();

            result.Page = page;

            return View(result);
        }
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = new UserEntity { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet("users/edit/{id}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost("users/edit/{id}")]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = await _userManager.FindByIdAsync(model.Id.ToString());
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(Guid id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(Guid id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = await _userManager.FindByIdAsync(model.Id.ToString());
                if (user != null)
                {
                    var _passwordValidator =
                    HttpContext.RequestServices.GetService(typeof(IPasswordValidator<UserEntity>)) as IPasswordValidator<UserEntity>;
                    var _passwordHasher =
                    HttpContext.RequestServices.GetService(typeof(IPasswordHasher<UserEntity>)) as IPasswordHasher<UserEntity>;

                    IdentityResult result =
                    await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Користувач не знайдений");
                }
            }
            return View(model);
        }
    }
}

WebForum/Views/Shared/_AdminLayout.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<header>
    <div class="d-flex justify-content-center aligns-items-center">
        <div>
            <a asp-controller="Admin" asp-action="Topics" class="btn btn-primary">Topics</a>
            <a asp-controller="Users" asp-action="Index" class="btn btn-primary">Користувачи</a>
        </div>
        @if (Context.Request.Path.ToString().Split("/").Last<String>().ToLower() != "admin")
        {
<a class="btn btn-primary rounded-circle" href="@(Context.Request.Path + "/create")">+</a>}
    </div>
</header>
<body class="d-flex flex-column min-vh-100">
    @RenderBody()
</body>

WebForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Forum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Вхід</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Реєстрація</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">Керування</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">

                                <a class="nav-link text-white" asp-controller="Account" asp-action="Profile">@User.Identity.Name </a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class=".bg-dark nav-link text-dark" type="submit" value="Exit" />
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="text-center text-white" style="background-color: #f1f1f1;">
        <!-- Grid container -->
        <div class="container pt-4">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-facebook-f"></i>
                </a>

                <!-- Twitter -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-twitter"></i>
                </a>

                <!-- Google -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-google"></i>
                </a>

                <!-- Instagram -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-instagram"></i>
                </a>

                <!-- Linkedin -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-linkedin"></i>
                </a>
                <!-- Github -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                   href="#!"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <i class="fab fa-github"></i>
                </a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2022 Copyright:
            <a class="text-dark">FreightTrans</a>
        </div>
        <!-- Copyright -->
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>